[telescope]
TelescopeDiameter = 8.
ZenithAngle = 0.0
ObscurationRatio = 0.16
Resolution = 128
TechnicalFoV = 120

[atmosphere]
Wavelength = 500e-9
L0 = 22.0
Cn2Weights = [1.00]
WindDirection = [0.0]
# Seeing = 0.8
# L0 = 22.0
# Cn2Weights = [0.67, 0.07, 0.10, 0.10, 0.06]
# Cn2Heights = [30, 562, 4500, 7750, 14000]
# WindSpeed = [12.3, 8.3, 30.4, 56, 32]
# WindDirection = [150, 79, -69, -7, -82]
# r0_Value = 0

[sources_science]
# Wavelength = [2.2e-06]
Zenith = [0.0]
Azimuth = [0.0]

[sources_HO]
Wavelength = [589e-9]
# Zenith = [0.0]
Azimuth = [0.0]
Height = 90000

[sources_LO]
# Wavelength = [2.2e-06]
# Zenith = [0.0]
Azimuth = [0.0]

[sensor_science]
PixelScale = 14
FieldOfView = 256

[sensor_HO]
WfsType = 'Shack-Hartmann'
Modulation = None
PixelScale = 800
FieldOfView = 8
# FieldOfView = 240
Binning = 1
NumberPhotons = [50.0]
SigmaRON = 0.2
ExcessNoiseFactor = 2.0
NumberLenslets = [30]
NoiseVariance = [None]

[sensor_LO]
WfsType = 'Shack-Hartmann'
Modulation = None
PixelScale = 510
FieldOfView = 8
# FieldOfView = 72
Binning = 1
NumberPhotons = [10.0]
SigmaRON = 0.2
Dark = 0.0
SkyBackground = 0.0
ExcessNoiseFactor = 2.0
NumberLenslets = [9]
NoiseVariance = [None]
WindowRadiusWCoG = 6
ThresholdWCoG = 0.0
NewValueThrPix = 0.0


[DM]
# NumberActuators = [41]
# DmPitchs = [0.2]
DmHeights = [0.0]
InfCoupling = [0.35]
AoArea = 'circle'

[RTC]
# LoopGain_HO = 0.5
# SensorFrameRate_HO = 1000.0
LoopDelaySteps_HO = 2
# LoopGain_LO = 0.4
# SensorFrameRate_LO = 500.0
LoopDelaySteps_LO = 2
